### ISSUE TITLE
pelican-photos 1.5.0 is now broken

### ISSUE THREAD

**Issue by SirLaffalot** [pelican-plugins/photos#109]
Pillow deprecated "textsize" a few versions back and now throws an error.

Pillow 10.1.0 throws an error:
ERROR    Could not process pages/page.md                                               log.py:94
                    'ImageDraw' object has no attribute 'textsize'  

Pillow now calls it "textlength"

I see it on line 1322...
            text_size = draw_watermark.textsize(
                self._pelican_settings["PHOTO_WATERMARK_TEXT"], font
            )

Sorry, not confident enough to open a pull request. See also https://github.com/k01ek/netbox-qrcode/issues/48 Broke their code too.

**Comment by jpulliam** [comment]
should be able to update to:
            text_size[0] = draw_watermark.textlength(
                self._pelican_settings["PHOTO_WATERMARK_TEXT"], font, direction="rtl"
            )
            text_size[1] = font.size

not sure if this fixes everything.I'll fiddle with it some more and open a pull request.

**Comment by phibos** [comment]
Is fixed by #110 . Thanks for your work.
