### ISSUE TITLE
Upgraded to 1.6.0 and watermark broken

### ISSUE THREAD

**Issue by Jeffmackinnon** [pelican-plugins/photos#123]
I upgraded from 1.5.0 to 1.6.0 but watermark is still not working. This is the error that I'm getting 

"photos: 'setting text direction, language or font features is not supported without libraqm'"

I have the following options in ``pelicanconf.py``

``PHOTO_WATERMARK = True``

``PHOTO_WATERMARK_TEXT = 'jeffmackinnon.com'``

If I make ``PHOTO_WATERMARK`` False it runs without issue.

I'm running pelican on windows within a pipenv environment.

**Comment by phibos** [comment]
Looks like Pillow is unable to find and/or load the libraqm library. Pillow is the library used by the photos plugin to modify images. Please have a look at the Pillow installation manual if every component has been installed successfully: https://pillow.readthedocs.io/en/latest/installation/building-from-source.html Looks like some additional steps have to be done to use font support on Windows.

**Comment by Jeffmackinnon** [comment]
> Looks like Pillow is unable to find and/or load the libraqm library. Pillow is the library used by the photos plugin to modify images. Please have a look at the Pillow installation manual if every component has been installed successfully: https://pillow.readthedocs.io/en/latest/installation/building-from-source.html Looks like some additional steps have to be done to use font support on Windows.

Thanks @phibos I will look into this soon and report back what I learned and whether there is a new/different issue when I do.

**Comment by phibos** [comment]
@Jeffmackinnon did you solve the issue?
