### ISSUE TITLE
Photos not processed for hidden posts or pages

### ISSUE THREAD

**Issue by Jeffmackinnon** [pelican-plugins/photos#36]
I created a hidden post where I plan to have the comprehensive gallery of all the photos in a certain category, however, the only way to make this work currently is to make the posts as published and then revise as hidden.

This works until I need tweak the theme and need to re-generate all the photos.

Is this something that can be fixed easily?

**Comment by phibos** [comment]
Thanks for reporting the issue. It has been fixed with #41 and will be included in the next release.
