### ISSUE TITLE
<class lines in output?

### ISSUE THREAD

**Issue by mcmikedermott** [pelican-plugins/photos#37]
The plugin works great - Thank you!
But when I run pelican to process my content, there is a stream of lines like this:

```
<class 'pelican.plugins.photos.photos.CaptionCache'>
<class 'pelican.plugins.photos.photos.ExifCache'>
```

I haven't counted - but I'm assuming one pair of these for each photo. Is that normal behavior? No errors or warnings, and everything works as it should.

Thanks for any thoughts.

**Comment by Jeffmackinnon** [comment]
I have noticed the same thing, and its on my list of things to figure out if it is because I don't have the caption/exif files in the folders. I would prefer to have these suppressed some how, because it means that I have to build outside VS Code as Code doesn't keep a large enough history.

**Comment by antonmosich** [comment]
This is already fixed in the current development version. Once the next release comes out it will no longer print those lines. The fix is in commit 2561b6bb77e7468914336b5099418076fb7ed3b1.

**Comment by phibos** [comment]
@antonmosich thanks for answering the question. You are right, the fix will be included in the next release.

**Comment by mcmikedermott** [comment]
Great - Thanks!
