### ISSUE TITLE
Pillow dependency is on a version with security alerts

### ISSUE THREAD

**Issue by offbyone** [pelican-plugins/photos#46]
I have a repository that's getting `pillow` 8 via this plugin, and it looks like that version has some known security advisories. I'd like to upgrade to Pillow 9, but that requires this plugin to do so. 

Do you have any plans for that? Is it as easy as "plug in the new version"?

**Comment by phibos** [comment]
You are right. I have used this plugin with Pillow 9.0.1 in some of my projects in the last weeks and I think it should be save to bump the version.

**Comment by offbyone** [comment]
Would you mind making a 1.3.1 release for this?
