### ISSUE TITLE
Image rotation is removed

### ISSUE THREAD

**Issue by zimmdi** [pelican-plugins/photos#49]
If you want to have images rotated by exif. This is removed.
def manipulate_exif(self, img: PILImage.Image) -> Tuple[PILImage.Image, str]:
is never called because
https://github.com/pelican-plugins/photos/blob/main/pelican/plugins/photos/photos.py#L1028-L1039
is commented out and 
im, exif_copy = manipulate_exif(im)
should be
im, exif_copy = self.manipulate_exif(im)
and
https://github.com/pelican-plugins/photos/blob/main/pelican/plugins/photos/photos.py#L1044-L1045
is commented out.

**Comment by phibos** [comment]
I will have a look at it in the next days.

**Comment by phibos** [comment]
This should have been fixed with #57 and has been merged into main and will be in the next release.
