### ISSUE TITLE
ARTICLE_SAVE_AS does not work in combination with inline images

### ISSUE THREAD

**Issue by EddyXorb** [pelican-plugins/photos#51]
When I use a non default location for ARTICLE_SAVE_AS, e.g.
`ARTICLE_SAVE_AS = "articles/{slug}.html"`
the images do not show up.

This is due to a missing slash in the generated image-reference.

My directories structure is as follows:

website
   - content
   - - articles
   - - - article.md
   - - images
   - - - image.jpg

and in article.md the image is referenced using

`![]({photo}image.jpg)`

In my case it outputs this:
`<p><a href="photos/image.jpg"><img alt="" src="photos/imaget.jpg"></a></p>`

The problem is the relative path. To make it failsafe it should be enough to prepend a slash before "photos" in the output, at least if the settings ARTICLE_SAVE_AS is set.

I think line 1545 of photos.py
``python
       if value.startswith("/"):
            value = value[1:]
``
should be touched for that.

**Comment by phibos** [comment]
Thanks for reporting the issue.

**Comment by phibos** [comment]
Should be fixed with #58 and has been merged into the main branch. For me the links where only broken if SITEURL was not set. Feel free to test.
