### ISSUE TITLE
Image not rotated per Exif data

### ISSUE THREAD

**Issue by stuieordie** [pelican-plugins/photos#59]
I found issue #49 (https://github.com/pelican-plugins/photos/issues/49) but not sure if this is the same behavior

I have a gallery with multiple images with different rotation data in the exif. I have `PHOTO_EXIF_AUTOROTATE` set to true in pelicanconf. When I load the page, the images are not rotated.

I do have the piexif library installed. 

I create the gallery with 

```
gallery: {photo}/20220828
```
in the new article markdown page. 

When I run `pelican -D -r -l` this is what I see for that file
```
INFO     photos: make photo(PID: 36255) /home/mstuart/Pictures/Personal/Blog/20220828/20220828_133110.jpg -> output/photos/20220828/20220828_133110.jpg        photos.py:580
           DEBUG    tag: ImageLength (257) - type: long (4) - value: b' \n\x00\x00'                                                                              TiffImagePlugin.py:815
           DEBUG    photos: Open file /home/mstuart/Pictures/Personal/Blog/20220828/20220828_133110.jpg                                                                   photos.py:823
           DEBUG    tag: DateTime (306) - type: string (2) Tag Location: 130 - Data Location: 202 - value: b'2022:08:28 13:29:42\x00'                            TiffImagePlugin.py:815
           DEBUG    tag: Orientation (274) - type: short (3) - value: b'\x06\x00'                                                                                TiffImagePlugin.py:815
           DEBUG    tag: DateTime (306) - type: string (2) Tag Location: 130 - Data Location: 202 - value: b'2022:08:28 13:31:10\x00' 

```

For comparison when I open this same image in GIMP, it sees asks if I want to rotate the photo and then does so correctly.

**Comment by phibos** [comment]
What version are you using? Version 1.3.0 or the source from the main branch? If you are using version 1.3.0 can you please try version 1.4.0. We have released this version just a few minutes ago with a lot of fixes.

**Comment by stuieordie** [comment]
I was using 1.3.0 via pip install. Confirmed images are rotating according to exif data now.

**Comment by phibos** [comment]
Thanks for testing the new version. I close this issue because we track the other problems in #62

**Comment by stuieordie** [comment]
I will upgrade to 1.4.0 and give it another test.

```
$ python3 -m pip show pelican-photos
Name: pelican-photos
Version: 1.3.0
Summary: Add a photo or a gallery of photos to an article
Home-page: https://github.com/pelican-plugins/photos
Author: Joaquim Baptista
Author-email: ***@***.***
License: AGPL-3.0
Location: /home/mstuart/.local/lib/python3.10/site-packages
Requires: pelican, piexif, Pillow
Required-by: 
```
