### ISSUE TITLE
Update README for How to make the gallery lightbox

### ISSUE THREAD

**Issue by stuieordie** [pelican-plugins/photos#65]
Just a documentation update but I found that in your example you link to the googleapis jsquery site using http://  - the lightbox gallery worked fine when I ran `pelican -r -l` on localhost, but when I deployed to my web server it did not. After inspecting the page, I found the following error

```
Mixed Content: The page at 'your-blog-name' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
```

After updating the template to use HTTPS it worked great.

I can take a stab at some new verbiage in the README if you'd like with a PR.

**Comment by phibos** [comment]
Would be great if you have an idea how to improve the documentation. Feel free to open a PR.
