### ISSUE TITLE
Example needs Markdown; Pillow 10+ has no `ANTIALIAS`

### ISSUE THREAD

**Issue by gucio321** [pelican-plugins/photos#92]
Hi
Im trying to build an example but it fails:
- it cannot parse `md` articles 
```diff
-pelican == 4.8.0
+pelican[markdown] == 4.8.0
```
- Also in newest Pillow it complains that `ANTIALIASING` is not there [ref](https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias)

**Comment by justinmayer** [comment]
Hi @gucio321. Thank you for reporting this.

I addressed the first problem via: aaa4d83966df4f4aee65275b4c01bb3700341963

I addressed the second problem via: 4ee68755c7f1e491b4ea280d3c7b78a04c861bb0

These fixes should appear in a packaged release soon, perhaps even by the end of the day today.
